spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
       native:
         search-locations: file:///run/media/gokult/common/repos/crm/config-repo

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071