spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/relatia-crm/config-repo.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8888
